### ISSUE TITLE
Document 'dbm' Requirement

### ISSUE THREAD

**Issue by tomschr** [pydoit/doit#111]
Trying `doit` inside a virtual environment without any `dodo.py` file fails with an `ImportError`.

I did the following steps to try doit:

1.  Create a new Python3 virtual environment
    ```
$ pyvenv env
```

2.  Activate the virtual env:
    ```
$ . env/bin/activate
```

3. Upgrade `pip` and `setuptools`:
    ```
$ pip install -U pip setuptools
```

4. Install `doit`:
   ```
$ pip install doit
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.                                                                                                                 
Collecting doit
  Using cached doit-0.29.0.tar.gz
Collecting six (from doit)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cloudpickle (from doit)
  Using cached cloudpickle-0.1.1-py2.py3-none-any.whl
Collecting pyinotify (from doit)
  Using cached pyinotify-0.9.6.tar.gz
Installing collected packages: six, cloudpickle, pyinotify, doit
  Running setup.py install for pyinotify
  Running setup.py install for doit
Successfully installed cloudpickle-0.1.1 doit-0.29.0 pyinotify-0.9.6 six-1.10.0
```

5. Run `doit`:
    ```
$ doit -h
Traceback (most recent call last):
  File "/local/repos/GH/dbcookbook/env/bin/doit", line 9, in <module>
    load_entry_point('doit==0.29.0', 'console_scripts', 'doit')()
  File "/local/repos/GH/dbcookbook/env/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/local/repos/GH/dbcookbook/env/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/local/repos/GH/dbcookbook/env/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/local/repos/GH/dbcookbook/env/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/local/repos/GH/dbcookbook/env/lib64/python3.4/site-packages/doit/__init__.py", line 31, in <module>
    from doit import loader
  File "/local/repos/GH/dbcookbook/env/lib64/python3.4/site-packages/doit/loader.py", line 12, in <module>
    from .task import DelayedLoader, Task, dict_to_task
  File "/local/repos/GH/dbcookbook/env/lib64/python3.4/site-packages/doit/task.py", line 15, in <module>
    from .dependency import UptodateCalculator
  File "/local/repos/GH/dbcookbook/env/lib64/python3.4/site-packages/doit/dependency.py", line 10, in <module>
    from dbm import dumb
ImportError: No module named 'dbm'
```

```
$ pip list
cloudpickle (0.1.1)
doit (0.29.0)
pip (7.1.2)
pyinotify (0.9.6)
setuptools (18.4)
six (1.10.0)

$ lsb_release -a
LSB Version:    n/a
Distributor ID: openSUSE project
Description:    openSUSE 13.2 (Harlequin) (x86_64)
Release:        13.2
Codename:       Harlequin

$ python --version
Python 3.4.1
```

**Comment by tomschr** [comment]
Argh, installing the package `python3-dbm` fixed the problem above. Sorry for the noise.

It would be good if this requirement should be documented somewhere.

**Comment by schettino72** [comment]
IMO opinion this an openSUSE bug. It is understandable that different DBM backends might come as separate OS packages. But `dbm.dumb` exists exactly to make sure every python installation has at least one valid DBM backed installed. 

Patches to improve docs are always welcome :) Apart to mention this SUSE peculiarity, it would be good to point that `dbm.dumb` is inefficient and the user should make sure it is using a "better" backend.
