### ISSUE TITLE
"reset-dep" command doesn't work

### ISSUE THREAD

**Issue by DarwinAwardWinner** [pydoit/doit#120]
With the following trivial `dodo.py` file in an otherwise empty directory:

```python
#!/usr/bin/env doit -f

from doit.tools import run_once

def task_create_file1():
    return {
        'actions': [ ['touch', 'file1'] ],
        'targets': ['file1'],
        'clean': True,
        'uptodate': [run_once],
    }

def task_copy_file1_to_file2():
    return {
        'actions': [ ['cp', 'file1', 'file2'] ],
        'file_dep': ['file1'],
        'targets': ['file2'],
        'clean': True,
    }
```

Running `doit reset-dep` produces the following:

```
$ doit reset-dep
processed create_file1
Traceback (most recent call last):
  File "/gpfs/home/rcthomps/.pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/gpfs/home/rcthomps/.pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/gpfs/home/rcthomps/.pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/cmd_base.py", line 405, in execute
    return self._execute(**exec_params)
  File "/gpfs/home/rcthomps/.pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/cmd_resetdep.py", line 68, in _execute
    self.dep_manager.save_success(task, result_hash=result)
  File "/gpfs/home/rcthomps/.pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/dependency.py", line 535, in save_success
    state = self.checker.get_state(dep, self._get(task.name, dep))
  File "/gpfs/home/rcthomps/.pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/dependency.py", line 435, in get_state
    return os.path.getmtime(dep)
  File "/gpfs/home/rcthomps/.pyenv/versions/2.7.11/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: 'file1'
$ echo $?
3
```

**Comment by DarwinAwardWinner** [comment]
Further info:

```
$ python --version
Python 2.7.11
$ pip list | grep doit
doit (0.29.0)

**Comment by schettino72** [comment]
what were you expecting to happen?

**Comment by DarwinAwardWinner** [comment]
I was expecting it to say that both tasks were not done.

**Comment by DarwinAwardWinner** [comment]
Is `doit reset-deps` only meant for running after a completion of `doit run`?

**Comment by schettino72** [comment]
> I was expecting it to say that both tasks were not done (and not throw an exception).

This is a command for developers... throwing an exception is ok IMO

**Comment by rbeagrie** [comment]
Would it be possible to revisit this? I would actually find it very useful to be able to run reset-dep when some files are missing. I'm willing to try to put together a PR if you don't mind adding this functionality?

**Comment by schettino72** [comment]
> I'm willing to try to put together a PR if you don't mind adding this functionality?

And what would be the result? Ignore the tasks with a missing file-dependency?
I am ok with that, just not by default. Just add an extra flag to the command to enable this functionality.
I do not remember how the output of this command looks like... but it should at least print a warning in this situation. 

And please create another issue. This one is messy already.
