### ISSUE TITLE
"doit list" fails if tasks contain non-ASCII characters in doc

### ISSUE THREAD

**Issue by DarwinAwardWinner** [pydoit/doit#125]
With the following `dodo.py`:

``` python
#!/usr/bin/env doit -f
# -*- coding: utf-8; -*-

def task_do_stuff():
    return {
        'doc': "This has unicode in it: résumé.",
        'actions': ["echo 'Did stuff'"],
        'verbosity': 2,
    }
```

running `doit list` produces: 

```
$ doit list
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/cmd_base.py", line 405, in execute
    return self._execute(**exec_params)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/cmd_list.py", line 152, in _execute
    self._print_task(template, task, status, list_deps, tasks)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/cmd_list.py", line 85, in _print_task
    self.outstream.write(template.format(**line_data))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128)
```

`doit run` still works, though.
##

**Comment by schettino72** [comment]
python 2?

master doesnt even support python2 anymore. If you create a branch from the last release and a pull request with this fix, I can push a new release.

**Comment by schettino72** [comment]
python2 is not supported anymore. so closing this...
