### ISSUE TITLE
Problem with using absolute paths for targets and dependencies

### ISSUE THREAD

**Issue by DGrady** [pydoit/doit#138]
It looks like there's some kind of problem with doit's file name tracking when using absolute paths. If a task defines targets and dependencies using absolute paths, doit tries to get information about these files even if they don't yet exist.

For example, this `dodo.py` file

```
from pathlib import Path

def task_first():

    target = str(Path('dummy.txt').resolve())

    return {
        'actions': [lambda: print("This is the first task.")],
        'targets': [target],
    }


def task_second():

    dep = str(Path('dummy.txt').resolve())
    target = str(Path('dummy2.txt').resolve())

    return {
        'actions': [lambda: print("This is the second task.")],
        'file_dep': [dep],
        'targets': [target],
    }
```

fails with the following stack trace when running `doit list`.

```
Traceback (most recent call last):
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/site-packages/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/site-packages/doit/cmd_base.py", line 273, in load_tasks
    return self._load_from(cmd, dodo_module, self.cmd_names)
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/site-packages/doit/cmd_base.py", line 247, in _load_from
    task_list = loader.load_tasks(members, cmd_list, cmd.execute_tasks)
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/site-packages/doit/loader.py", line 148, in load_tasks
    _process_gen()
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/site-packages/doit/loader.py", line 140, in _process_gen
    task_list.extend(generate_tasks(name, ref(), ref.__doc__))
  File "/Users/dgrady/Documents/doitest/dodo.py", line 5, in task_first
    target = str(Path('dummy.txt').resolve())
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/pathlib.py", line 1094, in resolve
    s = self._flavour.resolve(self)
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/pathlib.py", line 330, in resolve
    return _resolve(base, str(path)) or sep
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/pathlib.py", line 315, in _resolve
    target = accessor.readlink(newpath)
  File "/Users/dgrady/anaconda/envs/python3/lib/python3.5/pathlib.py", line 422, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dgrady/Documents/doitest/dummy.txt'
```

```
$ python --version
Python 3.5.1 :: Anaconda 2.5.0 (x86_64)
$ doit --version
0.29.0
lib @ /Users/dgrady/anaconda/envs/python3/lib/python3.5/site-packages/doit
```

**Comment by DGrady** [comment]
I'm sorry; I realized this is caused by `pathlib`, not by `doit`!
