### ISSUE TITLE
input() doesn't work when `-n` is used on the command line

### ISSUE THREAD

**Issue by TMiguelT** [pydoit/doit#177]
It seems to be as simple as this: if the `-n` (the [Parallel Execution](http://pydoit.org/cmd_run.html#parallel-execution) flag) is used, any `PythonInteractiveAction`s that use the built-in `input()` function fail with `EOFError: EOF when reading a line`.

Consider the following task (python3.6):
```python
def task_copy_bpipe_config():
    # Filepaths
    in_template = ROOT / 'pipeline/bpipe.config.template'
    out_template = ROOT / 'pipeline/bpipe.config'

    def action():
        # Prompt for user input
        queue = input('What queueing system do you use? "slurm", "torque", "pbspro", or "none" (no queueing system) are accepted.')
        options = {'slurm', "torque", "pbspro", "none"}
        if queue not in options:
            raise Exception(f'Queueing system must be one of: {", ".join(options)}')
        account = input('What account name do you want to use when running jobs in this system?') if not queue == 'none' else ''

        # Write out the new config file
        template = Template(in_template.read_text())
        out_template.write_text(template.render({
            'queue': queue,
            'account': account
        })) 

    return {
        'actions': [PythonInteractiveAction(action)],
        'targets': [out_template],
        'uptodate': [True]
    }   
```

When run with `-n` set, it fails as follows:
```
(python) ubuntu@michael-xl:/mnt/cpipe_install_test$ doit -n 1 install
-- generate_pipeline_id
-- copy_main_config
What queueing system do you use? "slurm", "torque", "pbspro", or "none" (no queueing system) are accepted..  copy_bpipe_config
########################################
TaskError - taskid:copy_bpipe_config
PythonAction Error
Traceback (most recent call last):
  File "/mnt/cpipe_install_test/tools/python/lib/python3.6/site-packages/doit/tools.py", line 218, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/mnt/cpipe_install_test/dodo.py", line 123, in action
    queue = input('What queueing system do you use? "slurm", "torque", "pbspro", or "none" (no queueing system) are accepted.')
EOFError: EOF when reading a line
```

When run without `-n` set, it succeeds, and prompts the user:
```
(python) ubuntu@michael-xl:/mnt/cpipe_install_test$ doit install
-- generate_pipeline_id
-- copy_main_config
.  copy_bpipe_config
What queueing system do you use? "slurm", "torque", "pbspro", or "none" (no queueing system) are accepted.
```

**Comment by schettino72** [comment]
i guess this is a bit of limitation of working with a terminal. if you have other threads constantly sending more output to the terminal window it would be really weird to type some input.

And of course that we would need a mechanism to route the input from the "control" thread to the one asking for input. 

I am more inclined to mark this as `wontfix` unless someone has a good idea on how to handle this...

**Comment by schettino72** [comment]
To tell you the truth I would not work on adding this feature myself. Tasks being interactive was not really a goal for `doit`.

Do you know you can pass arguments to specific tasks or pass "global" params to be used by tasks?

Another option if you really want to ask user to input something is to create a new command overwriting the `run` command where it asks for user input before actually starting the task execution.
