### ISSUE TITLE
Improve doit message when file from `file_dep` is missing

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit#211]
If a task requires an input file as declared in `file_dep`, one may get output as follows:

	(py36) javl@T810:~/devel/pydoit/samples/multi⟫ doit
	-- one:onetail_onetail
	-- one:onetail_twotail
	.  one:onetail_threetail

	Traceback (most recent call last):
	  File "/home/javl/devel/pydoit/samples/.tox/py36/lib/python3.6/site-packages/doit/doit_cmd.py", line 167
	, in run
	    return command.parse_execute(args)
	  File "/home/javl/devel/pydoit/samples/.tox/py36/lib/python3.6/site-packages/doit/cmd_base.py", line 120
	, in parse_execute
	    return self.execute(params, args)
	  File "/home/javl/devel/pydoit/samples/.tox/py36/lib/python3.6/site-packages/doit/cmd_base.py", line 403
	, in execute
	    return self._execute(**exec_params)
	  File "/home/javl/devel/pydoit/samples/.tox/py36/lib/python3.6/site-packages/doit/cmd_run.py", line 252,
	 in _execute
	    return runner.run_all(self.control.task_dispatcher())
	  File "/home/javl/devel/pydoit/samples/.tox/py36/lib/python3.6/site-packages/doit/runner.py", line 246,
	in run_all
	    self.run_tasks(task_dispatcher)
	  File "/home/javl/devel/pydoit/samples/.tox/py36/lib/python3.6/site-packages/doit/runner.py", line 213,
	in run_tasks
	    self.process_task_result(node, catched_excp)
	  File "/home/javl/devel/pydoit/samples/.tox/py36/lib/python3.6/site-packages/doit/runner.py", line 184,
	in process_task_result
	    self.dep_manager.save_success(task)
	  File "/home/javl/devel/pydoit/samples/.tox/py36/lib/python3.6/site-packages/doit/dependency.py", line 5
	12, in save_success
	    state = self.checker.get_state(dep, self._get(task.name, dep))
	  File "/home/javl/devel/pydoit/samples/.tox/py36/lib/python3.6/site-packages/doit/dependency.py", line 3
	94, in get_state
	    timestamp = os.path.getmtime(dep)
	  File "/home/javl/devel/pydoit/samples/.tox/py36/lib/python3.6/genericpath.py", line 55, in getmtime
	    return os.stat(filename).st_mtime
	FileNotFoundError: [Errno 2] No such file or directory: 'threehead_threetail'

I think, that for command `doit` it shall simply explain, that given file is
expected as file dependency and is missing. All stacktrace is useless as it only lists doit
internals which have nothing to do with the code, which could cause or fix the
problem.

**Comment by schettino72** [comment]
ok. agree.

**Comment by schettino72** [comment]
Actually, doit already would complain for missing file_dep *when it checks it*. The problem only arises when the check for up-to-date is short-circuit because doit figures out task is not up-to-date before checking `file_dep` (i.e. a missing target).

Also, probably you should get an error from your own action because it was supposed to use the `file_dep` somehow. So I think this will only be useful in case you have a misconfiguration on your dodo.py file.
