### ISSUE TITLE
"pip install doit" fails (before and after `brew upgrade python3`)

### ISSUE THREAD

**Issue by pkoppstein** [pydoit/doit#247]
```
$ uname -a
Darwin MacMini2017.local 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
# Before `brew upgrade python3`
$ pip install doit
Collecting doit
  Using cached doit-0.30.3.tar.gz
    Complete output from command python setup.py egg_info:
    This version of doit is only supported by Python 3.
    Please use doit==0.29.0 with Python 2.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/15/wd4cntyn53x87v4x86wxysyc0000gn/T/pip-build-gXLx4k/doit/
# same failure using sudo
$ brew upgrade python3
$ pip install doit
Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 544, in <module>
    main()
...
# Same error with `pip3 install doit`
```

**Comment by schettino72** [comment]
>  Please use doit==0.29.0 with Python 2.

```
# Same error with `pip3 install doit`
```
No traceback i do not believe you :smirk: 

Also I already released doit `0.31`, why would you get `0.30.3`???

**Comment by Kwpolska** [comment]
Try restarting your terminal, rebooting your machine, and perhaps reinstalling python from homebrew. Python 3 was recently renamed to `python` in Homebrew (along with all the executables).

**Comment by pkoppstein** [comment]
> Also I already released doit 0.31, why would you get 0.30.3???

That's what "pip install doit" found just a few seconds before the run shown in the original typescript. In any case, just now:

```
$ pip --no-cache-dir install doit
Collecting doit
  Downloading doit-0.30.3.tar.gz (235kB)
    100% |################################| 235kB 6.3MB/s 
 ...
```
> Please use doit==0.29.0 with Python 2.
```
$ pip install doit==0.29.0
Collecting doit==0.29.0
  Downloading doit-0.29.0.tar.gz (222kB)
    100% |################################| 225kB 3.3MB/s 
Collecting six (from doit==0.29.0)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting cloudpickle (from doit==0.29.0)
  Downloading cloudpickle-0.5.2-py2.py3-none-any.whl
Collecting macfsevents (from doit==0.29.0)
  Downloading MacFSEvents-0.8.1.tar.gz
Collecting configparser (from doit==0.29.0)
  Downloading configparser-3.5.0.tar.gz
Building wheels for collected packages: doit, macfsevents, configparser
  Running setup.py bdist_wheel for doit ... done
  Stored in directory: /Users/peter/Library/Caches/pip/wheels/29/ec/aa/4263b95fa3320cdb8efcf32cfd5d0052390d0bc13349ef9d73
  Running setup.py bdist_wheel for macfsevents ... done
  Stored in directory: /Users/peter/Library/Caches/pip/wheels/a3/89/cd/9b7f470d90a325e0ff38cd5d4508babcb31d4866329463a37c
  Running setup.py bdist_wheel for configparser ... done
  Stored in directory: /Users/peter/Library/Caches/pip/wheels/1c/bd/b4/277af3f6c40645661b4cd1c21df26aca0f2e1e9714a1d4cda8
Successfully built doit macfsevents configparser
Installing collected packages: six, cloudpickle, macfsevents, configparser, doit
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python@2/2.7.14_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/LICENSE.txt'
```

Please don't tell me to run "sudo pip ...."

And I have been using `homebrew`.

**Comment by vlcinsky** [comment]
@pkoppstein couple of things have to be clarified:
- what version of python and pip you are using: Try `python --version` and `pip --version`
- python you are installing into:
	- system python (this requires sudo regardless of your willingess to hear this instruction)
	- user profile python (`pip install --user ...` without sudo)
	- virtual python environment (this is the best option as it gives you complete control and does not spoil system python)
	- if using pyenv, there are more options to cover
- what python index (pypi) index you are using
	- none
	- file cache in your user profile
	- local pypi index (e.g. I use pydev-server, which does excellent service to me)
	- some custom external index
	- default index pypi.index.org


From what I have seen so far in your description it seems that:
- you are trying to install into system python (at least the last attempt)
- your may be using some custom pypi index as you repeatedly show it provides outdated doit version
- in case you install into python 2.x, you shall restrict doit version to `doit==0.29.` (or in other words `doit<=0.30.0` which seems simpler to remember for me)

I would recommend you to learn using virtualenv. I will assume you are python 3.x providing `venv` command:

```
$ python venv myvenv
$ source myvenv/bin/activate
(myvenv)$ python --version
(myvenv)$ pip --version
(myvenv)$ pip install doit  # pip install doit<=0.30.0 for python 2.7
```

If things are still surprising, more elaboration on pypi index used is needed.

**Comment by koliyo** [comment]
```
IOError: [Errno 13] Permission denied: '/usr/local/LICENSE.txt'
```
This is not a path that a python library should write to?
