### ISSUE TITLE
TypeError when failed task with dependency with --continue option

### ISSUE THREAD

**Issue by miyakogi** [pydoit/doit#249]
### How to reproduce

Make new directory with dodo.py as below:

```python
def task_flake8():
    return {'actions': ['flake8 dodo.py']}

def task_all():
    return {'actions': None, 'task_dep': ['flake8']}
```

Run `doit -c all`, then task `flake8` failes, and doit raises `TypeError`:

```
.  flake8
TaskFailed - taskid:flake8
Command failed: 'flake8 dodo.py' returned 1

UnmetDependency - taskid:all
flake8

<stdout>:
dodo.py:4:1: E302 expected 2 blank lines, found 1

Traceback (most recent call last):
  File "/home/takagi/.virtualenvs/arch/doittest/lib/python3.6/site-packages/doit/doit_cmd.py", line 172, in run
    return command.parse_execute(args)
  File "/home/takagi/.virtualenvs/arch/doittest/lib/python3.6/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/home/takagi/.virtualenvs/arch/doittest/lib/python3.6/site-packages/doit/cmd_base.py", line 416, in execute
    return self._execute(**exec_params)
  File "/home/takagi/.virtualenvs/arch/doittest/lib/python3.6/site-packages/doit/cmd_run.py", line 260, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/home/takagi/.virtualenvs/arch/doittest/lib/python3.6/site-packages/doit/runner.py", line 257, in run_all
    self.finish()
  File "/home/takagi/.virtualenvs/arch/doittest/lib/python3.6/site-packages/doit/runner.py", line 240, in finish
    self.reporter.complete_run()
  File "/home/takagi/.virtualenvs/arch/doittest/lib/python3.6/site-packages/doit/reporter.py", line 91, in complete_run
    show_err = task.verbosity < 1 or self.failure_verbosity > 0
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by schettino72** [comment]
Thanks for report. This is a critical regression bug.

I just pushed a fix into master. Also improved a bit the output formatting that was unreadable.
Please check if it is ok now.

I will make a bug-fix release over the weekend.

**Comment by miyakogi** [comment]
Thank you for fixing so quickly.
I have checked It's ok on master branch.
