### ISSUE TITLE
ModuleTaskLoader(): OSError when changing the path

### ISSUE THREAD

**Issue by assarbad** [pydoit/doit#310]
Consider the following Python scripts. It is important to have them into some subdirectory, here it is named `doit-test`, but the name does not matter.

### `doit-test/test1.py`
```python3
#!/usr/bin/python3
import doit
import os
import sys

def task_hello():
    """hello"""

    def python_hello(targets):
        with open(targets[0], "a") as output:
            output.write("Python says Hello World!!!\n")

    return {
        "actions": [python_hello],
        "targets": ["hello.txt"],
        "clean": True,
        }

if __name__ == "__main__":
    from doit.cmd_base import ModuleTaskLoader
    from doit.doit_cmd import DoitMain

    os.chdir(os.path.realpath(os.path.dirname(__file__)))
    sys.exit(DoitMain(ModuleTaskLoader(sys.modules[__name__])).run(sys.argv[1:]))
```

### `doit-test/test2.py`

```python3
#!/usr/bin/python3
import doit
import os

def task_hello():
    """hello"""

    def python_hello(targets):
        with open(targets[0], "a") as output:
            output.write("Python says Hello World!!!\n")

    return {
        "actions": [python_hello],
        "targets": ["hello.txt"],
        "clean": True,
        }

if __name__ == "__main__":
    os.chdir(os.path.realpath(os.path.dirname(__file__)))
    doit.run(globals())
```
These scripts should be pretty much equivalent anyway, and with respect to this issue they behave identically.

If you run these scripts in the folder in which they are located, all works as expected. However, when running them using a relative path we get this:

```
Traceback (most recent call last):
  File "/home/oliver/.local/lib/python3.5/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/home/oliver/.local/lib/python3.5/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/home/oliver/.local/lib/python3.5/site-packages/doit/cmd_base.py", line 389, in execute
    self, params, args)
  File "/home/oliver/.local/lib/python3.5/site-packages/doit/cmd_base.py", line 270, in load_tasks
    return self._load_from(cmd, self.mod_dict, self.cmd_names)
  File "/home/oliver/.local/lib/python3.5/site-packages/doit/cmd_base.py", line 254, in _load_from
    task_list = loader.load_tasks(members, cmd_list, cmd.execute_tasks)
  File "/home/oliver/.local/lib/python3.5/site-packages/doit/loader.py", line 129, in load_tasks
    funcs = _get_task_creators(namespace, command_names)
  File "/home/oliver/.local/lib/python3.5/site-packages/doit/loader.py", line 200, in _get_task_creators
    line = inspect.getsourcelines(ref)[1]
  File "/usr/lib/python3.5/inspect.py", line 931, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.5/inspect.py", line 762, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

This is somewhat unexpected and it does not help to import `linecache` and call `linecache.clearcache()` between instantiating the loader and calling `DoitMain().run()` either.

I discovered this when I changed the path before invoking `run()` ... but it's simpler to reproduce by giving a relative path to the script in question.

**Environment**
1. OS: Windows 10 and Ubuntu 16.04 respectively (error is the same except paths and line numbers in traceback)
2. Python version: 3.7.3 / 3.5.2
3. doit version: 0.31.1

----

The one workaround I have found was to use the following variation on the `DodoTaskLoader`:

```python3
#!/usr/bin/python3
import doit
import os
import sys

def task_hello():
    """hello"""

    def python_hello(targets):
        with open(targets[0], "a") as output:
            output.write("Python says Hello World!!!\n")

    return {
        "actions": [python_hello],
        "targets": ["hello.txt"],
        "clean": True,
        }

if __name__ == "__main__":
    from doit.cmd_base import TaskLoader
    from doit.doit_cmd import DoitMain

    class MyTaskLoader(TaskLoader):
        cmd_options = ()

        def load_tasks(self, cmd, params, args):
            from doit import loader
            module = loader.get_module(__file__, None, False)
            return self._load_from(cmd, module, self.cmd_names)

    sys.exit(DoitMain(MyTaskLoader()).run(sys.argv[1:]))
```

**Comment by schettino72** [comment]
It is a bug on python: https://bugs.python.org/issue15931  https://bugs.python.org/issue20443

**Comment by assarbad** [comment]
Damn. Thanks for pointing it out. Will see whether there is a better workaround, as the one I came up with has other unexpected side effects (global variables from said module are not visible inside functions from that module any longer ...).
