### ISSUE TITLE
default_tasks: wildcard selection crashes `doit clean`

### ISSUE THREAD

**Issue by madig** [pydoit/doit#344]
Given the following dodo.py:

```python
DOIT_CONFIG = {"default_tasks": ["t*"]}


def task_t1():
    return {"actions": ["echo task1"]}


def task_t2():
    return {"actions": ["echo task2"]}


def task_a1():
    return {"actions": ["echo task3"]}
```

`doit` works as expected:
```
> doit
.  t1
.  t2
```

`doit clean` will fail:
```
> doit clean
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\doit\doit_cmd.py", line 190, in run
    return command.parse_execute(args)
  File "c:\program files\python37\lib\site-packages\doit\cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "c:\program files\python37\lib\site-packages\doit\cmd_base.py", line 601, in execute
    return self._execute(**exec_params)
  File "c:\program files\python37\lib\site-packages\doit\cmd_clean.py", line 103, in _execute
    tree.build_nodes_with_deps(tasks, name)
  File "c:\program files\python37\lib\site-packages\doit\cmd_clean.py", line 131, in build_nodes_with_deps
    task = tasks[task_name]
KeyError: 't*'
```

Does the clean command intentionally not support wildcards?

**Environment**
1. OS: Windows 10 x64 1909
2. python version: 3.7.6
3. doit version: 0.32.0

**Comment by schettino72** [comment]
> Does the clean command intentionally not support wildcards?

Just need someone to implement it :grin:
