### ISSUE TITLE
doit no longer installs with setuptools 50.0.0

### ISSUE THREAD

**Issue by moltob** [pydoit/doit#370]
Probably related to https://github.com/pypa/setuptools/issues/2355. When now installing doit from TGZ (not from cached wheel), the installation fails, if setuptools are up-to-date (v50.0.0, released yesterday).

```
(venv) λ pip list
Package     Version
----------- -------
cloudpickle 1.6.0
pip         20.2.2
setuptools  50.0.0
wheel       0.35.1

(venv) λ pip --no-cache-dir install doit
Looking in indexes: https://artifactory.cc.bmwgroup.net/artifactory/api/pypi/ic-gen5-pypi/simple
Collecting doit
  Downloading https://artifactory.cc.bmwgroup.net/artifactory/api/pypi/ic-gen5-pypi/packages/packages/1f/89/b5e1dd4854b47c4f9e5250899c04e0cd0c9082c30ef619c0413ace20cf7a/doit-0.32.0.tar.gz (1.4 MB)
     |████████████████████████████████| 1.4 MB 467 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'd:\temp\doit-install-issue\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\q199925\\AppData\\Local\\Temp\\pip-install-3ovj31zb\\doit\\setup.py'"'"'; __file__='"'"'C:\\Users\\q199925\\AppData\\Local\\Temp\\pip-install-3ovj31zb\\doit\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\q199925\AppData\Local\Temp\pip-pip-egg-info-pztah4sa'
         cwd: C:\Users\q199925\AppData\Local\Temp\pip-install-3ovj31zb\doit\
    Complete output (17 lines):
    d:\temp\doit-install-issue\venv\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
      warnings.warn("Setuptools is replacing distutils.")
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\q199925\AppData\Local\Temp\pip-install-3ovj31zb\doit\setup.py", line 44, in <module>
        setup(name = 'doit',
      File "d:\temp\doit-install-issue\venv\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "d:\temp\doit-install-issue\venv\lib\site-packages\setuptools\__init__.py", line 145, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "d:\temp\doit-install-issue\venv\lib\site-packages\setuptools\dist.py", line 665, in parse_config_files
        self._parse_config_files(filenames=filenames)
      File "d:\temp\doit-install-issue\venv\lib\site-packages\setuptools\dist.py", line 572, in _parse_config_files
        filenames = self.find_config_files()
      File "d:\temp\doit-install-issue\venv\lib\site-packages\setuptools\_distutils\dist.py", line 353, in find_config_files
        sys_dir = os.path.dirname(sys.modules['distutils'].__file__)
    KeyError: 'distutils'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The root cause might be related to the `import pip` in this module's `setup.py`:

https://github.com/pydoit/doit/blob/6bb833d41c82b6fe1b36a1f9bcfeafa6b3c3133c/setup.py#L12

**Environment**
1. OS: Windows 10, Linux
2. python version: 3.6 - 3.8
3. doit version: 0.32.0

@ferraith FYI

**Comment by Kwpolska** [comment]
Pull request #369 fixes this bug by removing the pip import (which is not really necessary these days).

**Comment by schettino72** [comment]
Thanks guys. I will make another release in one hour or so...

**Comment by schettino72** [comment]
should be ok now. releases 0.33.0
