### ISSUE TITLE
errors with python2.6 on cent-os

### ISSUE THREAD

**Issue by johnerichumphries** [pydoit/doit#69]
Maybe this should not qualify as an issue as it does not list python 2.6 is a version of python that is tested against, but it seems that doit will not work when installed from pip, easy_install or source.  

Here is the error message I get when trying to run doit:
```python
[j@hbx ~]$ doit
Traceback (most recent call last):
  File "/usr/bin/doit", line 9, in <module>
    load_entry_point('doit==0.29.dev0', 'console_scripts', 'doit')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/doit-0.29.dev0-py2.6.egg/doit/__init__.py", line 33, in <module>
    from doit.doit_cmd import get_var
  File "/usr/lib/python2.6/site-packages/doit-0.29.dev0-py2.6.egg/doit/doit_cmd.py", line 11, in <module>
    from .plugin import PluginDict
  File "/usr/lib/python2.6/site-packages/doit-0.29.dev0-py2.6.egg/doit/plugin.py", line 86
    return {k: self.get_plugin(k) for k in self.keys()}
                                    ^
```

Sorry in advance if this is not an appropriate thing to file an issue on.

Thanks, -JE

**Comment by Kwpolska** [comment]
@schettino72, maybe you should add some explicit info on ancient Python support, or investigate blocking installs there?
@johnerichumphries Let Python 2.6 die already.

**Comment by schettino72** [comment]
both on package metadata and on written doc it says doit supports py 2.7 and 3.2 to 3.4. If you check the CHANGES file you can see when each release support was added and removed. That's explicit enough for me...

**Comment by johnerichumphries** [comment]
@Kwpolska, I couldn't agree more, centos still ships with 2.6 and the admin will not upgrade.

I use doit on my own machine and really like it, so figured it was worth checking. Back to using make!

Sorry for filing what seems to be an invalid issue and thanks for the help.
