### ISSUE TITLE
Failing on callable tasks with keyword only args

### ISSUE THREAD

**Issue by Hinidu** [pydoit/doit#74]
Hello! Thank you for the great tool!
I found that problem when I was trying to use `shutil.copyfile`:
```py
from shutil import copyfile

def task_copyfile():
    return {'actions': [(copyfile, ['foo', 'bar'])]}
```
It fails with the following error message:
```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\doit\doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "C:\Python34\lib\site-packages\doit\cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "C:\Python34\lib\site-packages\doit\cmd_base.py", line 405, in execute
    return self._execute(**exec_params)
  File "C:\Python34\lib\site-packages\doit\cmd_run.py", line 239, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "C:\Python34\lib\site-packages\doit\runner.py", line 238, in run_all
    self.run_tasks(task_dispatcher)
  File "C:\Python34\lib\site-packages\doit\runner.py", line 204, in run_tasks
    catched_excp = self.execute_task(node.task)
  File "C:\Python34\lib\site-packages\doit\runner.py", line 166, in execute_task
    return task.execute(sys.stdout, sys.stderr, self.verbosity)
  File "C:\Python34\lib\site-packages\doit\task.py", line 376, in execute
    action_return = action.execute(task_stdout, task_stderr)
  File "C:\Python34\lib\site-packages\doit\action.py", line 368, in execute
    kwargs = self._prepare_kwargs()
  File "C:\Python34\lib\site-packages\doit\action.py", line 337, in _prepare_kwargs
    self.args, self.kwargs)
  File "C:\Python34\lib\site-packages\doit\action.py", line 44, in _prepare_kwargs
    argspec = inspect.getargspec(func)
  File "C:\Python34\lib\inspect.py", line 936, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```

I'm using python 3.4, according to the [documentation](https://docs.python.org/3.4/library/shutil.html#shutil.copyfile) argument `follow_symlinks` was added to `shutil.copyfile` in python 3.3. With python 2.7 code above works without any problem.
Of course that particular problem can be solved on my side with `lambda` for example but I thought that it could be the useful information for you.

**Comment by schettino72** [comment]
Thanks for the report.

According to [docs](https://docs.python.org/3/library/inspect.html#inspect.getargspec) `inspect.getargspec()` is deprecated on python3. So doit should use `inspect.getfullargspec()` when available(python3).

@Hinidu, Can you give  a try implementing a patch?

**Comment by Hinidu** [comment]
@schettino72, of course! I'll give it a try next week.
