### ISSUE TITLE
Potential bug in `list -s --all`

### ISSUE THREAD

**Issue by jgosmann** [pydoit/doit#90]
When running doit with the arguments `list -s --all`, I am getting the following exception:
```
U cconv                           
Traceback (most recent call last):
  File "/home/jgosmann/.local/lib/python2.7/site-packages/doit/doit_cmd.py", line 121, in run
    return command.parse_execute(args)
  File "/home/jgosmann/.local/lib/python2.7/site-packages/doit/cmd_base.py", line 84, in parse_execute
    return self.execute(params, args)
  File "/home/jgosmann/.local/lib/python2.7/site-packages/doit/cmd_base.py", line 278, in execute
    return self._execute(**exec_params)
  File "/home/jgosmann/.local/lib/python2.7/site-packages/doit/cmd_list.py", line 157, in _execute
    self._print_task(template, task, status, list_deps)
  File "/home/jgosmann/.local/lib/python2.7/site-packages/doit/cmd_list.py", line 88, in _print_task
    task_status = self.dep_manager.get_status(task, None)
  File "/home/jgosmann/.local/lib/python2.7/site-packages/doit/dependency.py", line 501, in get_status
    uptodate_result = utd(*args, **utd_kwargs)
  File "/home/jgosmann/.local/lib/python2.7/site-packages/doit/task.py", line 537, in __call__
    dep_task = self.tasks_dict[self.dep_name]
TypeError: 'NoneType' object has no attribute '__getitem__'
```
This might be my own fault as I am using my own task loader and maybe I screw up the construction of the tasks (this makes also non-trivial to provide an actual minimal example). However, everything seems to work fine when executing the tasks. Also, what makes me believe that this might be a bug in doit is that `tasks_dict` is explicitely set to `None` in `cmd_list.py` on line 88.

**Comment by jgosmann** [comment]
I was running doit 0.27, problem is fixed in 0.28.
