### ISSUE TITLE
doit throws unhelpful exception when subtask does not exist

### ISSUE THREAD

**Issue by merten** [pydoit/doit#92]
First of all thanks for this awesome framework - it helped me a lot!

While this is no functional problem it makes it hard to use for users.
When I request a target where the basename exist but not the subtask doit fails with an exception unrelated to the real problem.

Minimal example:

    def task_example():
        for sub in ['a','b']:
            yield { 'actions' : ["echo %s" % sub],
                    'name'    : sub,
                    'verbosity' : 2,
                    'uptodate': [False]}

When I now run `doit example:c` I get the following traceback:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/doit/doit_cmd.py", line 165, in run
        return command.parse_execute(args)
      File "/usr/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
        return self.execute(params, args)
      File "/usr/lib/python2.7/site-packages/doit/cmd_base.py", line 405, in execute
        return self._execute(**exec_params)
      File "/usr/lib/python2.7/site-packages/doit/cmd_run.py", line 176, in _execute
        self.control.process(self.sel_tasks)
      File "/usr/lib/python2.7/site-packages/doit/control.py", line 203, in process
        self.selected_tasks = self._filter_tasks(task_selection)
      File "/usr/lib/python2.7/site-packages/doit/control.py", line 185, in _filter_tasks
        loader.basename = basename
    AttributeError: 'NoneType' object has no attribute 'basename'

**Comment by schettino72** [comment]
fixed on: https://github.com/pydoit/doit/commit/d4e4851061f54c17ae7e01cbebbe08b41f8b7b60

Thanks I think this is a small but important issue.

And thanks for doing a bug report "the right way"!
